# This is a basic workflow to help you get started with Actions

name: Terraform CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab (temp)
  workflow_dispatch:

jobs:
  terraform:
    env:
      AWS_REGION: 'eu-west-2'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: terraform fmt
        run: echo terraform fmt
      
      - name: terraform validate
        run: echo terraform validate
      
      - name: trivy
        run: echo trivy config ./

      - name: terraform-docs 
        run: echo terraform-docs markdown --output-file=README.md
      
      - name: terraform init
        run: echo terraform init

      - name: terraform plan
        run: echo terraform plan